ares_ui:
  avatar:
    margin_left: 3
    path: /home/daniel/tron/programas/TR/assets/ares/ares-neon.png
    size: 10
    z_index: 3
  footer:
    height: 1
    margin_left: 3
    path: /home/daniel/tron/programas/TR/assets/ui/layaout/separador.gif
    width: 120
    y_offset: 10
    z_index: 1
  header:
    height: 3
    margin_left: 3
    path: /home/daniel/tron/programas/TR/assets/ui/layaout/separador.gif
    width: 40
    y_offset: 0
    z_index: 1
  thinking:
    size: 10
    spinners:
    - /home/daniel/tron/programas/TR/assets/ui/layaout/spiner1.gif
    - /home/daniel/tron/programas/TR/assets/ui/layaout/spinner2.gif
    - /home/daniel/tron/programas/TR/assets/ui/layaout/spinner3.gif
    - /home/daniel/tron/programas/TR/assets/ui/layaout/spinner4.gif
    - /home/daniel/tron/programas/TR/assets/ui/layaout/spinner5.gif
    - /home/daniel/tron/programas/TR/assets/ui/layaout/spinner 6.gif
    - /home/daniel/tron/programas/TR/assets/ui/layaout/spinner7.gif
    z_index: 4
content:
  ares_color: cyan
  margin_left: 7
  margin_top: 0
  thinking_index: 5
  user_color: green
user_ui:
  avatar:
    margin_left: 3
    path: /home/daniel/tron/programas/TR/assets/user/user-emoji.png
    size: 10
    z_index: 3
  footer:
    height: 1
    margin_left: 3
    path: /home/daniel/tron/programas/TR/assets/ui/layaout/separador.gif
    width: 100
    y_offset: 8
    z_index: 1
  header:
    height: 2
    margin_left: 3
    path: /home/daniel/tron/programas/TR/assets/ui/layaout/separador.gif
    width: 30
    y_offset: 0
    z_index: 1
