content:
  color: cyan
  margin_left: 7
  margin_right: 4
  margin_top: 0
footer:
  separator:
    height: 2
    margin_left: 0
    path: /home/daniel/tron/programas/TR/assets/ui/layaout/separador_inferirior_central_contra_90_recorte_vert_40_estira_horiz_120.gif
    width: 65
    y_offset: 10
    z_index: 2
header:
  separator:
    height: 3
    margin_left: 7
    path: /home/daniel/tron/programas/TR/assets/ui/layaout/separador.gif
    width: 40
    y_offset: 0
    z_index: 1
  width_pct: 0.25
identity:
  ares:
    margin_left: 3
    margin_right: 3
    path: /home/daniel/tron/programas/TR/assets/ares/ares-neon.png
    size: 10
    z_index: 3
thinking:
  current_index: 5
  size: 10
  spinners:
  - /home/daniel/tron/programas/TR/assets/ui/layaout/spiner1.gif
  - /home/daniel/tron/programas/TR/assets/ui/layaout/spinner2.gif
  - /home/daniel/tron/programas/TR/assets/ui/layaout/spinner3.gif
  - /home/daniel/tron/programas/TR/assets/ui/layaout/spinner4.gif
  - /home/daniel/tron/programas/TR/assets/ui/layaout/spinner5.gif
  - /home/daniel/tron/programas/TR/assets/ui/layaout/spinner 6.gif
  - /home/daniel/tron/programas/TR/assets/ui/layaout/spinner7.gif
  z_index: 4
